# 워크플로우의 이름 지정
name: CI/CD
#워크플로가 시작될 조건 지정
on:
  push:
    branches: [ main ]
jobs:
  build:
    # 실행 환경 지정
    runs-on: ubuntu-latest
    # 실행 스텝 지정
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - run: touch ./Learner/src/main/resources/application.properties

      - run: echo "${{secrets.APPLICATION}}" > ./Learner/src/main/resources/application.properties

      - uses: actions/upload-artifact@v4
        with:
          name: application.properties
          path: ./Learner/src/main/resources/application.properties

      - name: Grant execute permission for gradlew
        run: chmod +x ./Learner/gradlew

      - name: Build with Gradle
        run: ./Learner/gradlew clean build

      # 현재 시간 가져오기
      - name: Get current time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DDTHH-mm-ss
          utcOffset: "+09:00"

      # 배포용 패키지 경로 저장
      - name: Set artifact
        run: echo "artifact=$(ls ./Learner/build/libs)" >> $GITHUB_ENV

      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{secrets.AWS_ACCESS_KEY}}
          aws_secret_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          application_name: grepp-web
          environment_name: Grepp-web-env
          version_label: github-action-${{steps.current-time.outputs.formattedTime}}
          region: ap-northeast-2
          deployment_package: ./Learner/build/libs/${{env.artifact}}